version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}
      POSTGRES_PORT: ${db_port}
    ports:
      - "54321:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - toggl-network
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - ./alembic:/app/alembic
    command:
      - sh
      - entrypoint.sh
    depends_on:
      - postgres
    networks:
      - toggl-network
  cron:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    command:
      - sh
      - cron-schedules/cron-entrypoint.sh
    networks:
      - toggl-network


volumes:
  alembic: 
  postgres:
networks:
  toggl-network: